name: Redis

on:
  push:
    branches: [ "develop" ]
  pull_request:
  
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
      
      - name: Init Terraform
        run: terraform init

      - name: Terraform plan
        id: plan
        run: terraform plan

      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve
